builds:
  - main: ./cmd
    binary: net
    goos:
      - darwin
    ldflags:
      - ""
    goarch:
      - amd64
  - main: ./cmd
    binary: macOS_nodpi/net
    id: netcap_macOS_nodpi
    goos:
      - darwin
    ldflags:
      - ""
    flags:
      - -tags=nodpi
  - main: ./cmd
    id: netcap_nodpi
    binary: net
    env:
    #- CGO_ENABLED=1
    # experiments to compile godpi with nDPI module
    #- CC=/usr/local/Cellar/mingw-w64/7.0.0_2/bin/x86_64-w64-mingw32-gcc
    #- CXX=/usr/local/Cellar/mingw-w64/7.0.0_2/bin/x86_64-w64-mingw32-g++
    #- LDFLAGS="-L/usr/local/opt/libpcap/lib -L/usr/local/Cellar/liblinear/2.30/lib -s -w -lndpi -lpcap -lm -pthread"
    #- CFLAGS="-I/usr/local/Cellar/libpcap/1.9.1/include/"
    #- CPPFLAGS="-I/usr/local/opt/libpcap/include -I/usr/local/Cellar/liblinear/2.30/include -I/usr/local/Cellar/mingw-w64/7.0.0_1/toolchain-x86_64/x86_64-w64-mingw32/include"
    #- PKG_CONFIG_PATH="/usr/local/opt/libpcap/lib/pkgconfig"

    # For more info refer to: https://golang.org/doc/install/source#environment
    goos:
      - windows

    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`.
    ldflags:
      - "" # -L /usr/local/opt/libpcap/lib -s -w
    flags:
      - -tags=nodpi
    goarch:
      - amd64

archives:
  -
    # Defaults are any files matching `LICENCE*`, `LICENSE*`,
    # `README*` and `CHANGELOG*` (case-insensitive).
    files:
      - LICENSE
      - README.md
      - types/cpp/*
      - types/csharp/*
      - types/java/*
      - types/js/*
      - types/python/*
      - types/rust/*
      - types/swift/*
      - types/netcap.pb.go
    # Disables the binary count check - TODO add multiple archives
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    github:
      owner: dreadl0ck
      name: homebrew-formulas
    homepage: "https://github.com/dreadl0ck/netcap"
    description: "A framework for secure and scalable network traffic analysis"

before:
  hooks:
  # You may remove this if you don't use go modules.
  #- go mod download
  # you may remove this if you don't need go generate
  #- go generate ./...