workDir: ~/go/src/github.com/dreadl0ck/netcap/analyze/dnn

command: python3
args:
  - -u
  - train.py
  - -features=18
  - -socket=True
  - -encodeCategoricals=False
  - -batchSize=96000
  - -lstm=True
  #- -batchSize=32000

epochs: 5

auditRecords:
  - Connection

